version: '3.2'

volumes:
  postgres_rew:
    driver: local

services:

  postgres_rew:
    image: library/postgres:latest
    container_name: rew_db
    volumes:
      - type: volume
        target: /var/lib/postgresql
    environment:
      POSTGRES_DB: rew_db
      POSTGRES_USER: rew
      POSTGRES_PASSWORD: rew777
    ports:
      - 5455:5432